### ISSUE TITLE
how to use mqtt-pwn with brokers that require TLS

### ISSUE THREAD

**Issue by michyArya** [akamai-threat-research/mqtt-pwn#4]
Hello,
I was trying mqtt-pwn and I didn't find an option to use TLS to talk to a broker that requires. Do you know of another way to use TLS with this tool?

Thank you,
Arya

**Comment by Den1al** [comment]
Yes, there’s a pending pull request that is being reviewed as we speak. I’ll update this issue when it’s merged.

**Comment by Den1al** [comment]
I merged the pull request, now it’s possible to connect using TLS.

**Comment by michyArya** [comment]
thank you!

**Comment by amefonaffia** [comment]
Hi! This is still an issue for me and there is currently no information in the documentation of how this connection using TLS works.
